version: '3.8'

services:
  unified-server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SERVER_NAME=unified-server
      - SERVER_VERSION=1.0.0
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
      - LOG_LEVEL=INFO
    volumes:
      - ./examples:/app/examples:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s